version: "3.9"

services:

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_personapp
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: contrasena
      MARIADB_DATABASE: persona_db
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pcontrasena >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:5.0
    container_name: mongo_personapp
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: contrasena
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mongo --username root --password contrasena --authenticationDatabase admin --eval \"db.adminCommand('ping')\" >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personapp_api
    depends_on:
      mariadb:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Conexión MariaDB
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/persona_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: contrasena
      # Conexión MongoDB
      SPRING_DATA_MONGODB_URI: mongodb://root:contrasena@mongo:27017/persona_db?authSource=admin
      # Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDB103Dialect

volumes:
  mariadb_data:
  mongo_data:

